module.exports = {
  eslint: {
    dirs: ['pages', 'utils', 'constants', 'components', 'typings'],
  },
  i18n: {
    locales: ['en-US'],
    defaultLocale: 'en-US',
  },
  images: {
    domains: [
      'upload.wikimedia.org',
      'www.moma.org',
      'collectionapi.metmuseum.org',
      'www.moca.org',
      'media.nga.gov',
      'www.artic.edu',
      'www.joanmitchellfoundation.org',
      'bordercrossingsmag.com',
      'www.phaidon.com',
      'images.weserv.nl',
      'www.pamm.org',
      'live-caribbean-cultural-institute.pantheonsite.io',
      'uploads8.wikiart.org',
      'images.metmuseum.org',
      'www.diaart.org',
      'api.smk.dk',
      'iip-thumb.smk.dk',
      'learn.ncartmuseum.org',
      'ncartmuseum.org',
      'leiko.info',
      'd3swacfcujrr1g.cloudfront.net',
      'ursfischer.com',
      'artlogic-res.cloudinary.com',
      'www.jornada.com.mx',
      'www.surdoc.cl',
      'i0.wp.com',
      'pbs.twimg.com',
      'www.arte-online.net',
      'old.museotamayo.org',
      'cmoa-collection-images.s3.amazonaws.com',
      'emuseum.mfah.org',
      'emuseum.vassar.edu',
      'www.artfixdaily.com',
      'whitneymedia.org',
      'en.wikipedia.org',
      'www.centrepompidou.fr',
      'www.christies.com',
      'media.mutualart.com',
      'sarahcharlesworth.net',
      'i.pinimg.com',
      'www.park-books.com',
      'gulbenkian.pt',
      'img.bndlyr.com',
      'd1lfxha3ugu3d4.cloudfront.net',
      'd7hftxdivxxvm.cloudfront.net',
      'hammer.ucla.edu',
      'www.galleryhyundai.com',
    ],
  },
};
