module.exports = {
  eslint: {
    dirs: ['pages', 'utils', 'constants', 'components', 'typings'],
  },
  i18n: {
    locales: ['en-US'],
    defaultLocale: 'en-US',
  },
  images: {
    domains: [
      'upload.wikimedia.org',
      'www.moma.org',
      'collectionapi.metmuseum.org',
      'www.moca.org',
      'media.nga.gov',
      'www.artic.edu',
      'www.joanmitchellfoundation.org',
      'bordercrossingsmag.com',
      'www.phaidon.com',
      'images.weserv.nl',
      'www.pamm.org',
      'live-caribbean-cultural-institute.pantheonsite.io',
      'uploads8.wikiart.org',
      'images.metmuseum.org',
      'www.diaart.org',
      'api.smk.dk',
      'iip-thumb.smk.dk',
      'learn.ncartmuseum.org',
      'ncartmuseum.org',
      'leiko.info',
      'd3swacfcujrr1g.cloudfront.net',
      'ursfischer.com',
    ],
  },
};
