// This is an autogenerated file, do not modify directly
declare namespace NodeJS {
  interface ProcessEnv {
    DATABASE_URL: string;
    PASSWORD: string;
    USERNAME: string;
    JWT_SECRET: string;
    SPOTIFY_CLIENT_ID: string;
    SPOTIFY_CLIENT_SECRET: string;
  }
}
