name: Lint

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-linters:
    name: Run linters
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: Regenerate the prisma client
        run: pnpm run prisma:regenerate
      - name: Run linting
        run: pnpm lint
      - name: Check Typescript
        run: pnpm tsc
